# Personalize your website info here
title:          Sheree Watson
tagline:          'Professional Website for Sheree Watson'
description:      'Website and Blog for Sheree Watson'
url:              http://watsoshe.github.io
author:
  name:           'Sheree Watson'
  url:            

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
